//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reservationTicket.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int id { get; set; }
        public Nullable<int> Tre_id { get; set; }
        public int Bus_id { get; set; }
        public string depart { get; set; }
        public string destination { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
